runtime: python

api_version: 1

threadsafe: true


runtime_config:
    python_version: 3

# [START handlers]

handlers:

- url: /static

  static_dir: static

- url: /.*

  script: main.app

# [END handlers]