runtime: python37

entrypoint: gunicorn -b :$PORT main:app
# [START handlers]

handlers:

- url: /musyk/static

  static_dir: musyk/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# [END handlers]